ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
ALTER SESSION SET NLS_LANGUAGE = 'KOREAN';

-- 트레이너 정보 테이블 생성
drop table Boogie_Trainer;

CREATE TABLE Boogie_Trainer (
    USER_ID VARCHAR2(30),
    PASSWD VARCHAR2(20) CONSTRAINT Boogie_Trainer_PASSWD_nn NOT NULL,
    NICKNAME VARCHAR2(45) CONSTRAINT Boogie_Trainer_NICKNAME_nn NOT NULL,
    REGDATE DATE DEFAULT SYSDATE CONSTRAINT Boogie_Trainer_REGDATE_nn NOT NULL,
    EXP NUMBER(7) CONSTRAINT Boogie_Trainer_EXP_nn NOT NULL,
    PROFILE_IMG VARCHAR2(50),
    DELETED NUMBER(1) DEFAULT 0 CONSTRAINT Boogie_Trainer_DELETED_nn NOT NULL,
    CONSTRAINT Boogie_Trainer_USER_ID_pk PRIMARY KEY(USER_ID),
    CONSTRAINT Boogie_Trainer_PASSWD_ck CHECK(LENGTH(PASSWD) BETWEEN 4 AND 20),
    CONSTRAINT Boogie_Trainer_NICKNAME_ck CHECK(LENGTH(NICKNAME) BETWEEN 2 AND 15),
    CONSTRAINT Boogie_Trainer_EXP_ck CHECK(EXP >= 0),
    CONSTRAINT Boogie_Trainer_DELETED_ck CHECK(DELETED IN (0, 1))
);



--트레이너 정보 테이블 더미 데이터

--관리자 더미 데이터
INSERT INTO BoogieTrainer(USER_ID, PASSWD, NICKNAME, EXP, PROFILE_IMG)
VALUES ('boogi@google.com', 'boogi123', 'BIJUGI', 100000, 'profile1.jpg');

--일반 회원 더미 데이터
INSERT INTO BoogieTrainer(USER_ID, PASSWD, NICKNAME, EXP, PROFILE_IMG)
VALUES ('red@google.com', 'red456', 'RED',0, 'profile2.jpg');
INSERT INTO BoogieTrainer(USER_ID, PASSWD, NICKNAME, EXP, PROFILE_IMG)
VALUES ('green@google.com', 'green456', 'Green',0, 'profile2.jpg');
INSERT INTO BoogieTrainer(USER_ID, PASSWD, NICKNAME, EXP, PROFILE_IMG)
VALUES ('gold@google.com', 'gold456', 'Mokho',0, 'profile2.jpg');
INSERT INTO BoogieTrainer(USER_ID, PASSWD, NICKNAME, EXP, PROFILE_IMG)
VALUES ('silver@google.com', 'silver456', 'Seongho',0, 'profile2.jpg');
INSERT INTO BoogieTrainer(USER_ID, PASSWD, NICKNAME, EXP, PROFILE_IMG)
VALUES ('ruby@google.com', 'ruby456', 'Yunjin', 0, 'profile2.jpg');
INSERT INTO BoogieTrainer(USER_ID, PASSWD, NICKNAME, EXP, PROFILE_IMG)
VALUES ('sapphire@google.com', 'sapphire456', 'Bomi', 0, 'profile2.jpg');
INSERT INTO BoogieTrainer(USER_ID, PASSWD, NICKNAME, EXP, PROFILE_IMG)
VALUES ('diamond@google.com', 'diamond456', 'Nancheon', 0, 'profile2.jpg');
INSERT INTO BoogieTrainer(USER_ID, PASSWD, NICKNAME, EXP, PROFILE_IMG)
VALUES ('pearl@google.com', 'pearl456', 'Bichna', 0, 'profile2.jpg');
INSERT INTO BoogieTrainer(USER_ID, PASSWD, NICKNAME, EXP, PROFILE_IMG)
VALUES ('black@google.com', 'black456', 'Noganju', 0, 'profile2.jpg');
INSERT BoogieTrainer(USER_ID, PASSWD, NICKNAME, EXP, PROFILE_IMG)
VALUES ('white@google.com', 'white456', 'Iris', 0, 'profile2.jpg');

-- 유저 좋아요 테이블 생성
drop table USER_LIKE;

CREATE TABLE USER_LIKE (
    USER_ID VARCHAR2(30),
    STAMPBOOK_ID NUMBER(6),
    CONSTRAINT USER_LIKE_USER_ID_fk FOREIGN KEY (USER_ID) REFERENCES Boogie_Trainer(USER_ID),
    CONSTRAINT USER_LIKE_STAMPBOOK_ID_fk FOREIGN KEY (STAMPBOOK_ID) REFERENCES STAMPBOOK(STAMPBOOK_ID),
    CONSTRAINT USER_LIKE_pk PRIMARY KEY (USER_ID, STAMPBOOK_ID)
);

--스탬프 북 테이블 생성
drop table STAMPBOOK;

CREATE TABLE STAMPBOOK (
    STAMPBOOK_ID NUMBER(6), 
    TITLE VARCHAR2(60) CONSTRAINT STAMPBOOK_TITLE_nn NOT NULL ,
    DESCRIPTION VARCHAR2(1500) CONSTRAINT STAMPBOOK_DESCRIPTION_nn NOT NULL,
    USER_ID VARCHAR2(30) CONSTRAINT STAMPBOOK_USER_ID_nn NOT NULL,
    STAMPBOOK_REGDATE DATE DEFAULT SYSDATE CONSTRAINT STAMPBOOK_STAMPBOOK_REGDATE_nn NOT NULL,
    LIKECOUNT NUMBER(6) DEFAULT 0 CONSTRAINT STAMPBOOK_LIKECOUNT_nn NOT NULL,
    DELETED NUMBER(1) DEFAULT 0 CONSTRAINT STAMPBOOK_DELETED_nn NOT NULL,
    CONSTRAINT STAMPBOOK_STAMPBOOK_ID_pk PRIMARY KEY(STAMPBOOK_ID),
    CONSTRAINT STAMPBOOK_TITLE_ck CHECK (LENGTH(TITLE) BETWEEN 1 AND 20),
    CONSTRAINT STAMPBOOK_DESCRIPTION_ck CHECK (LENGTH(DESCRIPTION) BETWEEN 1 AND 500),
    CONSTRAINT STAMPBOOK_DELETED_ck CHECK(DELETED IN (0, 1)),
    CONSTRAINT STAMPBOOK_USER_ID_fk FOREIGN KEY (USER_ID) REFERENCES Boogie_Trainer(USER_ID)
);

--스탬프 댓글 테이블 생성 (ORA-00972: 식별자가 너무 깁니다.,STAMP_COMMENT -> STB_CMT)
drop table STAMP_COMMENT;

CREATE TABLE STAMP_COMMENT (
    COMMENT_ID NUMBER(7) CONSTRAINT STB_CMT_COMMENT_ID_nn NOT NULL,
    STAMPBOOK_ID NUMBER(6),
    USER_ID VARCHAR2(30) CONSTRAINT STB_CMT_USER_ID_nn NOT NULL,
    "COMMENT" VARCHAR2(750) CONSTRAINT STB_CMT_COMMENT_nn NOT NULL,
    WRITE_DATE DATE DEFAULT SYSDATE CONSTRAINT STB_CMT_WRITE_DATE_nn NOT NULL,
    DELETED NUMBER(1) DEFAULT 0 CONSTRAINT STB_CMT_DELETED_nn NOT NULL,
    CONSTRAINT STB_CMT_STAMPBOOK_ID_fk FOREIGN KEY (STAMPBOOK_ID) REFERENCES STAMPBOOK(STAMPBOOK_ID),
    CONSTRAINT STB_CMT_USER_ID_fk FOREIGN KEY (USER_ID) REFERENCES Boogie_Trainer(USER_ID),
    CONSTRAINT STB_CMT_COMMENT_ID_pk PRIMARY KEY(COMMENT_ID),
    CONSTRAINT STB_CMT_DELETED_ck CHECK(DELETED IN (0, 1)
));

CREATE INDEX COMMENT_ID ON STAMPBOOK_COMMENT (STAMPBOOK_ID);

-- 유저 선택 테이블 생성
drop table USER_PICK;

CREATE TABLE USER_PICK (
    USER_ID VARCHAR2(30),
    STAMPBOOK_ID NUMBER(6),
    PICK_DATE DATE DEFAULT SYSDATE CONSTRAINT USER_PICK_PICK_DATE_nn NOT NULL,
    COMPLETE_DATE DATE,
    CONSTRAINT USER_PICK_pk PRIMARY KEY (USER_ID, STAMPBOOK_ID)
);

--스탬프 테이블 생성
drop table STAMP;

CREATE TABLE STAMP (
    STAMPBOOK_ID NUMBER,
    STAMPNO NUMBER(3) CONSTRAINT STAMP_STAMPNO_nn NOT NULL,
    PLACE_ID NUMBER,
    CONSTRAINT STAMP_STAMPNO_ck CHECK (STAMPNO BETWEEN 1 AND 99),	 
    CONSTRAINT STAMP_PLACE_ID_fk FOREIGN KEY (PLACE_ID) REFERENCES PLACE(PLACE_ID),
    CONSTRAINT STAMP_pk PRIMARY KEY(STAMPBOOK_ID, STAMPNO)
);

--유저 스탬프 정보 테이블 생성
drop table USER_STAMP_HISTORY;

CREATE TABLE USER_STAMP_HISTORY (
    USER_ID VARCHAR2(30),
    STAMPBOOK_ID NUMBER(6),
    STAMPNO NUMBER(3),
    UPLOAD_IMG VARCHAR2(500),
    STAMPED_DATE DATE,
    USER_STAMP_HISTORY_DATE DATE DEFAULT SYSDATE CONSTRAINT USH_nn NOT NULL,
    CONSTRAINT USH_pk PRIMARY KEY (USER_ID, STAMPBOOK_ID, STAMPNO),
    CONSTRAINT USH_USER_ID_fk FOREIGN KEY (USER_ID) REFERENCES Boogie_Trainer(USER_ID),  
    CONSTRAINT USH_BOOK_ID_fk FOREIGN KEY (STAMPBOOK_ID, STAMPNO) REFERENCES STAMP(STAMPBOOK_ID, STAMPNO)
);
;

-- 명소 정보 테이블 생성
drop table PLACE;

CREATE TABLE PLACE (
    PLACE_ID NUMBER(4),
    NAME VARCHAR2(300) CONSTRAINT PLACE_NAME_nn NOT NULL,
    TYPE NUMBER(3) CONSTRAINT PLACE_TYPE_nn NOT NULL,
    ADDR VARCHAR2(300) CONSTRAINT PLACE_ADDR_nn NOT NULL,
    LAT VARCHAR2(20) CONSTRAINT PLACE_LAT_nn NOT NULL,
    LON VARCHAR2(20)CONSTRAINT PLACE_LON_nn NOT NULL,
    THUMBNAIL VARCHAR2(500),
    CONTENTS_ID VARCHAR2(11),    
    CONSTRAINT PLACE_PLACE_ID_pk PRIMARY KEY (PLACE_ID)
);

-- 명소 정보 상세 테이블 생성
drop table PLACE_DETAIL;

CREATE TABLE PLACE_DETAIL (
    PLACE_ID NUMBER(4),
    TEL VARCHAR2(200),
    DETAIL VARCHAR2(1500),
    PAY VARCHAR2(1500),
    TRAFFIC VARCHAR2(1500),
    IMG VARCHAR2(500),
    HOMEPAGE VARCHAR2(500),
    OPEN VARCHAR2(1500),
    CLOSE VARCHAR2(1500),
    FACILITY VARCHAR2(1500),
    constraint PLACE_DETAIL_PLACE_ID_fk FOREIGN KEY (PLACE_ID) REFERENCES PLACE(PLACE_ID)
);

CREATE INDEX PLACE_ID ON PLACE_DETAIL (PLACE_ID);

INSERT INTO PLACE_DETAIL (PLACE_ID, TEL, DETAIL, PAY, IMG, HOMEPAGE, OPEN, CLOSE, FACILITY)
VALUES (1, '051-701-5648', '해운대 미포철길', '무료', 'example.jpg', 'www.bluelinepark.com', '09:00 AM', '06:00 PM', '주차장'),
       (2, '051-605-4128', '황령산 레포츠공원', '무료', 'example.jpg', 'https://www.jsports.or.kr/bbs/content.php?co_id=07_01', '09:00 AM', '06:00 PM', '와이파이, 주차장');
----------------------------------
COMMIT;

-- 결과 출력 활성화
SET TERMOUT ON

-- SELECT 문 실행
SELECT * FROM USER;
SELECT * FROM USER_LIKE;
SELECT * FROM STAMPBOOK;
SELECT * FROM STAMPBOOK_COMMENT;
SELECT * FROM USER_PICK;
SELECT * FROM USER_STAMP_HISTORY;
SELECT * FROM STAMP;
SELECT * FROM PLACE;
SELECT * FROM PLACE_DETAIL;

EXIT

